### ISSUE TITLE
‘Files’ section references regarding `limit` property misleading

### ISSUE THREAD

**Issue by silllli** [getkirby/getkirby.com#1120]
I think the references regarding the `limit` property of a ‘files’ section are misleading ([here](https://getkirby.com/docs/reference/panel/sections/files#section-properties) and [here](https://getkirby.com/docs/reference/panel/sections/files#limits)).

It reads

> Sets the number of items per page. If there are more items the pagination navigation will be shown at the bottom of the section.

and

> The limit property sets how many files will be shown per page. If there are more entries in the section, the pagination navigation will be shown at the bottom of the section.

but it actually sets a limit for the pagination in the _selection dialog_, not the pagination at the bottom of the section.

This makes me wonder how I actually can control the pagination at the bottom of the section. Or am I confusing something?

**Comment by texnixe** [comment]
This is about a files section. A files section doesn't have a selection dialog. You probably confuse this with a [files **field** ](https://getkirby.com/docs/reference/panel/fields/files#pagination)which is a special form of select field, where the limit sets the number of items in the Picker.

Closing this because the provided information is correct.

In a files field you currently cannot paginate the selected items.

**Comment by silllli** [comment]
You are right! Sorry. This is what happened (the words ‘sections’ and ‘files’ were too close for my brain):

```
sections:
  selection:
    type: fields
    fields:
      selection:
        type: files
        limit: 25
```

**Comment by texnixe** [comment]
You might want to upvote this feature request: https://kirby.nolt.io/169

**Comment by silllli** [comment]
> You might want to upvote this feature request: https://kirby.nolt.io/169

Thanks, in fact I think that would be useful.
