### ISSUE TITLE
$page->panelUrl() not listed in Reference navigation

### ISSUE THREAD

**Issue by sebastiangreger** [getkirby/getkirby.com#1135]
Happy New Year, Team Kirby :fireworks: 

Function `panelUrl()` is marked as `@internal` [here](https://github.com/getkirby/kirby/blob/0d2751af7cb478df14f30fac47fe9a2cd3b38114/src/Cms/Page.php#L1015) which apparently omits it from being rendered in the Reference navigation tree, while the documentation is indeed accessible at https://getkirby.com/docs/reference/objects/page/panel-url

This is a pretty handy method to build "Edit page" links in the frontend -- is there a specific reason this is hidden from the reference?

**Comment by distantnative** [comment]
It's there for me, you just have to switch to "advanced" view (that's why it's marked for with `@internal`):

<img width="1358" alt="Screen Shot 2021-01-02 at 18 43 59" src="https://user-images.githubusercontent.com/3788865/103463153-95ac6300-4d2a-11eb-813a-4d72a04f9de3.png">

<img width="1348" alt="Screen Shot 2021-01-02 at 18 44 11" src="https://user-images.githubusercontent.com/3788865/103463157-993fea00-4d2a-11eb-9866-48520765b4d7.png">

**Comment by sebastiangreger** [comment]
@distantnative Oh my, I completely overlooked that "basic/advanced" switch 🙄 ...as I was already browsing `$page` subpages (the view with two scrollable nav trees on the left).

User error. Thanks for the pointer; glad to see it's there!
