### ISSUE TITLE
Plugin Assets: Explain How To Get Generated Timestamped URLs

### ISSUE THREAD

**Issue by neildaniels** [getkirby/getkirby.com#148]
The [Plugin Assets](https://getkirby.com/docs/guide/plugins/plugin-basics#plugin-assets) documentation leaves me confused as to how I should actually be getting these re-mapped asset URLs.

For example, let's say I have a plugin that has a JavaScript file in the assets folder and a snippet (that should output a `<script>` tag).

I'm very confused as to what I should be in my snippet in this example, because I've tried some different strings to pass to the `js()` helper function, and none of them actually point to a file (and it's not timestamped).

**Comment by texnixe** [comment]
Is this still relevant or has this been fixed?

**Comment by neildaniels** [comment]
@texnixe I never figured out how to "automatically" get it to add the timestamps. Doesn't look like that document ever clarified how that should happen, so I'm still in the dark.

**Comment by texnixe** [comment]
The documentation says that the timestamps should be added automatically but in fact, that doesn't seem to be the case. That is either a bug in the docs or a bug in Kirby.

@bastianallgeier, @distantnative, @lukasbestle?

**Comment by lukasbestle** [comment]
I checked the [source code](https://github.com/getkirby/kirby/blob/b8846772d3cc2fabe4e84c5b7f128dcd0b6e4202/src/Cms/PluginAssets.php#L51-L83) and you are right – timestamping doesn't currently happen. I think it should though.

Also there's currently no method that returns the public URL for a plugin asset for use in a snippet as originally reported by @neildaniels. The `PluginAssets::resolve()` method claims to do that in the docblock, but it actually returns a response object. I think there should be something like:

```php
$kirby->plugin('my-plugin')->assetUrl($filename)
```

Pinging @bastianallgeier because he is the one who originally wrote the `PluginAssets` class.
