### ISSUE TITLE
Overriding config from plugin

### ISSUE THREAD

**Issue by afbora** [getkirby/getkirby.com#1500]
An option cannot overwrite if defined in config.php because of `A::merge($pluginOptions, $coreOptions)`. If it is not defined, it can be set as follows. I think this info should be document.

````php
<?php

kirby()->extend([
    'options' => ['debug' => true]
]);

Kirby::plugin('my/plugin');
````

**Comment by lukasbestle** [comment]
To be honest I feel like this is only a hack and not a feature that should actually be used by plugins.

**Comment by afbora** [comment]
Yes, it's kind of a hack. So should we turn this from hacking into a feature?

**Comment by lukasbestle** [comment]
Well, I wonder what the real world use case would be. Plugins could set core options to default values, e.g. a plugin with multilang enhancements could set `'languages' => true`. But is this really necessary in practice?

IMO it's much better to explain such options in the plugin `README` so that the dev can enable them in `config.php`. Then the dev always knows which Kirby options are set to which value and doesn't need to search through all plugins to find out the option value. I imagine it could be a support nightmare if something in the site breaks because a plugin has set an option and then neither the dev nor we will realize why that is the case.

**Comment by afbora** [comment]
I know the days when I really needed this feature, but I don't remember what they are now 🙈. I think it's better to keep this information as a hack for now 👍
