### ISSUE TITLE
Check why html pages are delivered through assets.getkirby.com

### ISSUE THREAD

**Issue by texnixe** [getkirby/getkirby.com#1962]
https://discord.com/channels/525634039965679616/525641819854471168/1031546234361618452
https://forum.getkirby.com/t/prevent-keycdn-from-serving-html-pages/27991/2

**Comment by distantnative** [comment]
@bastianallgeier @texnixe are we sure that KeyCDN is involved? It seems to me that Kirby by default delivers all pages also to any subdomain. E.g. in our local sandbox with the staterkit, I can also just access it via `https://foo.sandbox.test/`

**Comment by lukasbestle** [comment]
assets.getkirby.com is the proxy domain for KeyCDN, so all requests go through KeyCDN. Our server gets the KeyCDN headers but otherwise doesn't know which domain it's serving on. We use this for the update check (serving the `security.json` and the plugin JSONs through KeyCDN as well).

Maybe we could detect KeyCDN requests by their request headers and redirect those requests or respond them with HTTP 400.
