### ISSUE TITLE
Failed to start Kirby

### ISSUE THREAD

**Issue by gethob** [getkirby/getkirby.com#1996]
Hi everyone, I have a problem trying to run kirby, both PHP versions 8.1 and 8.2 have the same result. Could you please help me to solve this issue?

**Issue with Reference**  
1. ```php -S 127.0.0.1:8000 kirby/router.php```  produces the output: [Tue Apr  4 10:47:46 2023] PHP 8.1.17 Development Server (http://127.0.0.1:8000) started
2. Open the Url ```http://127.0.0.1:8000/de``` in browser. Output Fatal error: Uncaught RuntimeException: Could not find resource 'js/zepto.min.js' in any resource paths.(searched: C:\kirby-cms\kirby/assets (...\kirby/assets with slash and backslash in path looks suspicious to me)
3. Typing the URL http://127.0.0.1:8000/panel forwards to http://127.0.0.1:8000/panel/installation and produces the same error as in step. 2: Output Fatal error: Uncaught RuntimeException: Could not find resource 'js/zepto.min.js' in any resource paths.(searched: C:\kirby-cms\kirby/assets

**Expected**  
Kirby home page with content

**Screenshots**  
described in 2. & 3. under the section **Issue with Reference**

**Comment by lukasbestle** [comment]
It looks like you are using a custom theme. A core Kirby installation does not come with the Zepto.js library (and does not need it to function).

Please try a fresh installation of Kirby's Starterkit first to rule out issues in your setup.

I'm closing this issue because this repository (getkirby.com) is for the Kirby website. For help we have our forum at https://forum.getkirby.com. I'm sure we will find a solution for your problem over there. 🙂

**Comment by gethob** [comment]
thank you for your response. I fixed it, the issue was rather because of php.ini hat to have some extensions activated.
