### ISSUE TITLE
nginx recipe should probably incorporate, or point to, security guide?

### ISSUE THREAD

**Issue by danburzo** [getkirby/getkirby.com#2064]
**Issue with Reference**  

I’ve not had enough first-experience with nginx to tell if the rules [provided in the nginx recipe](https://getkirby.com/docs/cookbook/setup/nginx) are comprehensive enough for a production site, but the recipe doesn’t mention the requirements from the [Security guide](https://getkirby.com/docs/guide/security) at all. 

**Expected**  

An equivalent of the `.htaccess` rules that ship with PlainKit and StarterKit could be included in the nginx recipe. Alternativeley, a prominent box that points out that the nginx config is not comprehensive and points to the Security guide would be welcome.

In case the nginx config _does_ cover Kirby’s security needs, a short explanation of how it works would also be greatly appreciated.

**Comment by lukasbestle** [comment]
@pReya Are you available to extend the recipe with examples or pointers for secure configuration? As far as I can see, the following are currently missing:

- Pointer to Let's Encrypt and how to enforce HTTPS (also not in the default Kirby `.htaccess` because it is often handled by the server configuration, but for nginx a quick note/pointer would be great)
- Block access to the `content`, `site`, `kirby` and dot folders

**Comment by pReya** [comment]
> @pReya Are you available to extend the recipe with examples or pointers for secure configuration? As far as I can see, the following are currently missing:
> 
>     * Pointer to Let's Encrypt and how to enforce HTTPS (also not in the default Kirby `.htaccess` because it is often handled by the server configuration, but for nginx a quick note/pointer would be great)
> 
>     * Block access to the `content`, `site`, `kirby` and dot folders

I'll try to add some more info on these points during the week.
