### ISSUE TITLE
Enhance troubleshooting section

### ISSUE THREAD

**Issue by texnixe** [getkirby/getkirby.com#260]
https://forum.getkirby.com/t/most-common-errors-gotchas-when-developing-with-kirby/4237

**Comment by fvsch** [comment]
Kirby could provide a `debug()` function that is an enhanced `var_dump()` with some pretty printing and protections against recursion on objects.

Currently, `var_dump($page)` will take an awful lot of CPU time to generate a very big output. Maybe that's understandable, but `var_dump($page->somefield)` and `var_dump($page->somefield())` will do the same thing.

I mention `var_dump` because it's a common answer to "how do I debug things simply in PHP?". Using `echo` is another one, but in many instances it gives little information and does not let you differentiate between an empty field and a non-existent field, for instance.

So having an official `debug` function with readable output and avoiding recursion on objects could help. I could try writing it as a plugin, if there's any interest in that.

**Comment by texnixe** [comment]
This was added in 2.4.0
