### ISSUE TITLE
Reference: long titles in sidebar broken

### ISSUE THREAD

**Issue by distantnative** [getkirby/getkirby.com#404]
<img width="367" alt="Screenshot 2019-03-12 at 12 07 18" src="https://user-images.githubusercontent.com/3788865/54195633-77270900-44bf-11e9-811b-6cccf967259c.png">

**Comment by fabianmichael** [comment]
@distantnative Is fixed in my branch now, will merge into master soon. Chrome seems to have very bad support for `word-wrap` and related properties. Only fix I could come up with was by adding zero-width spaces before each slash in the entry title using str_replace. Also added a tiny script to remove these invisible chars before copying anything to clipboard.
