### ISSUE TITLE
Improve requirements section

### ISSUE THREAD

**Issue by texnixe** [getkirby/getkirby.com#610]
https://forum.getkirby.com/t/please-extend-the-requirements-section-in-the-kirby-3-documentation/14812

**Comment by GiantCrocodile** [comment]
I agree: There were some posts about Kirby 3 being broken on upload because some PHP module or setting wasn't installed or set properly. In all of these cases, it was a mess to debug the situation. We should add information about:

- required PHP modules
- required PHP hashing function
- last/newest known working PHP version

I think especially bullet point no. 3 is helpful to track down issues like https://github.com/getkirby/kirby/issues/1812

**Comment by texnixe** [comment]
@GiantCrocodile  Do we know what the issue is?

**Comment by GiantCrocodile** [comment]
You mean regarding the specific issue I've mentioned @texnixe? I don't think so but most likely it's some kind of serverside (PHP setup) or Windows specific problem.

**Comment by texnixe** [comment]
We can't really list more PHP modules apart from what we already have documented. The PHP docs don't really give away what module is needed for what type of core functionality. Also, individual PHP versions might have bugs that may or may not affect a certain functionality.

If you run into issues please report them in the forum so that we can look into it on a case by case basis.

**Comment by GiantCrocodile** [comment]
I don't agree with just closing this ticket; To me, a minimum to extend/change:

- clarify "PHP 7.1+": We had cases where PHP 7.3 or other versions caused issues because of incompatiblity. Saying PHP 7.1 is as specific as just PHP 7 and thus not much of a help. At least mention the version we know which runs as latest version (because it works on your site or on some demo/test server). We should provide a maximum. Something like: "Fully operational under PHP 7.1 to 7.3". If it's too much afford to maintain these two numbers, we have to at least clarify the support: Anything above PHP 7.1 will be supported and if it doesn't work, Kirby devs will provide a hotfix release as soon as possible as a minor version.

- the PHP hashing (?) function is known to be required and can be missing (there was dev work needed to find out what was wrong; so it's quite an afford for both sides). So this is an one time maintaining information which is forever valid and thus doesn't have to be maintained later on again.

- Do we need an information regarding the possibility/must have (I'm not sure if there's a working Kirby 3 config option for this) to be able to maintain a proper timezone in PHP.ini file? I remember threads where the datetime field was wrong because the PHP timezone wasn't properly set.

Regarding the issue I've linked here: Will a developer check this out before this issue is closed and validates if this is happening NOT due to a missing requirement? I think this has to be done because we had an in detail discussion about this issue and didn't find a solution nor a reason why it occurs. To me this is a quite strong indication that there is some kind of requirement not met; although there's no PHP error logged.

It's hard to maintain this meta information stuff, but it is really important for new customers and ppl. who run the demo or work in productive and face errors which are not happening on the test or dev system.

**Comment by lukasbestle** [comment]
> clarify "PHP 7.1+": We had cases where PHP 7.3 or other versions caused issues because of incompatiblity.

We always support all stable PHP versions that are actively supported by the PHP team. We actually [recommend using the latest stable release](https://getkirby.com/docs/guide/security#secure-your-server__use-the-latest-stable-php-version) and we test for each new PHP release as soon as it's out.

But the requirements are always the minimum requirements, which is why you won't find a maximum version there – explaining all that would blow up the length of the requirements section. We want to keep it as concise as possible.

> the PHP hashing (?) function is known to be required and can be missing (there was dev work needed to find out what was wrong; so it's quite an afford for both sides). So this is an one time maintaining information which is forever valid and thus doesn't have to be maintained later on again.

It's not the only PHP feature that can be missing from a PHP installation. It seems like you can pretty much disable everything when compiling PHP. As @texnixe explained, we can't possibly list all PHP features we use (the list would be *incredibly* long and still incomplete), so this is always something we need to check on a case by case basis when a user has issues running Kirby on their server.

> Do we need an information regarding the possibility/must have (I'm not sure if there's a working Kirby 3 config option for this) to be able to maintain a proper timezone in PHP.ini file? I remember threads where the datetime field was wrong because the PHP timezone wasn't properly set.

I have added this to the [troubleshooting page](https://getkirby.com/docs/guide/troubleshooting/installation).

> Regarding the issue I've linked here: Will a developer check this out before this issue is closed and validates if this is happening NOT due to a missing requirement? I think this has to be done because we had an in detail discussion about this issue and didn't find a solution nor a reason why it occurs. To me this is a quite strong indication that there is some kind of requirement not met; although there's no PHP error logged.

When we handle support requests, we always first check if there's an obvious setup error. Some issues are unfortunately so bizarre that it takes some time to find the issue. And the issue you linked to doesn't look like an obvious setup issue – you would get PHP errors then.

**Comment by GiantCrocodile** [comment]
Thanks for your effort, both of you!
