### ISSUE TITLE
[Docs] Explain difference between activity timeout and duration timeout

### ISSUE THREAD

**Issue by GiantCrocodile** [getkirby/getkirby.com#733]
A more detailled explanation would be nice (what is an activity timeout and what counts for it? Why is there an activity timeout like why is a duration timeout not enough?): https://getkirby.com/docs/reference/system/options/session#durationlong

**Comment by lukasbestle** [comment]
See https://getkirby.com/docs/guide/sessions. Let us know if there are any open questions not answered there.

**Comment by GiantCrocodile** [comment]
In respect to my understanding, this doesn't answer these two basic questions:

1. Why is an activity timeout required next to a duration timeout? What is the benefit of this or why is an duration timeout not enough? 
2. What activity is enough to renew the activity timeout? Is any click enough? Any click on any button/link? Any action within the editor? Refreshing the page? etc.

Is the idea of the duration timeout that there are people with browsers which won't delete the cookies on every browser closing event and thus they can reopen the page and stay logged in? Wouldn't they be logged out by the activity timeout because it's shorter? It might make sense to me if the activity timeout is only checked if the user has an active instance (browser tab open). So the activity timeout won't trigger if the user is logged in but no panel of Kirby 3 open.

**Comment by lukasbestle** [comment]
> 1. Why is an activity timeout required next to a duration timeout? What is the benefit of this or why is an duration timeout not enough?

The duration and the timeout achieve two different goals:

- The **duration** is used by the session generation and renewal logic. The timestamp in the session ID is the expiry time, which is calculated based on the session start time + the duration. The duration is therefore an absolute measurement that doesn't depend on the session activity. If the duration has passed and the session was not renewed, it is expired. The duration therefore protects against attacks where the session ID is known to the attacker for some reason. By choosing a shorter duration, you can reduce the time that old leaked ID can do any harm, even if kept active by the user and/or the attacker.
- The **timeout** is based on the last session activity. It therefore protects against attacks where a user logs into the Panel on a shared/public browser and forgets to log out again. The session is automatically invalidated if Kirby hasn't heard from that browser for a while.

As these are implementation details though, I don't think we should add them to the docs as that will make the docs more complex and harder to read for most users who don't need the technical details.

> 2. What activity is enough to renew the activity timeout? Is any click enough? Any click on any button/link? Any action within the editor? Refreshing the page? etc.

See the page you linked to:

<img width="762" alt="Bildschirmfoto 2019-11-03 um 16 32 56" src="https://user-images.githubusercontent.com/1595007/68087585-aed03000-fe57-11e9-91e7-b7ad807d419b.png">

You don't need to do anything, you only need to have the page open in the foreground.

I have now converted that sentence to an info box to make it more visible.

**Comment by GiantCrocodile** [comment]
Am I right that if I keep the panel window open in the foreground, the session will last longer than the duration timeout and activity timeout?

**Comment by lukasbestle** [comment]
Yes.

**Comment by GiantCrocodile** [comment]
I'm not sure that the current implementation is a good idea security wise:

I understand the idea behind the duration timeout and the activity timeout but if this is meant to be a security feature, it's a bad idea to have a session last forever if the browser won't close. This can be abused by third parties who got access to the session one time and it makes this scenario unpossible:

`The timeout is based on the last session activity. It therefore protects against attacks where a user logs into the Panel on a shared/public browser and forgets to log out again. The session is automatically invalidated if Kirby hasn't heard from that browser for a while.`

If the browser is still open, the session is active forever. Be it in an cyber café or because you were disturbed and had to leave (emergency call, fire alarm, evacuation or whatever). In any of these scenarios, the browser is still open and third parties may access the system. To me it sounds misleading if the both security features are avoided by just not closing the browser or the specific tab of the browser.

I'm aware that this became more a security question rather than the original doc question/enhancement request. Originally, this doubt was what I suspected and why I asked because I wasn't too sure about if I understand the situation right according to the docs.

**Comment by lukasbestle** [comment]
Secure implementations can only ever protect against the attacks they were designed to protect against. And the design of a secure implementation is the direct outcome of the goals that were set when the solution was conceived.

In my [post above](https://github.com/getkirby/getkirby.com/issues/733#issuecomment-549148172) I have explained the goals we set for our solution and how the implementation implements those goals.

What you propose is a third goal: Protect users who don't lock their devices against attackers with physical access. But that goal can't be implemented in a server-side session implementation as you can easily circumvent any further protection we add from the server-side by faking activity immediately after the user leaves their computer. The only real way to protect against this kind of attack would be a permanent biometrics check (e.g. the face of the user needs to be in front of the device at all times, otherwise the user is logged out). You don't even find such protections in popular operating systems.

In the end it's always a trade-off between user experience and absolute security. We really value good security, but not at any cost, otherwise users will disable security features completely that could have otherwise provided considerable security.

Kirby 2 didn't have the automatic session renewal in the background and people complained all the time that their content edits were lost after just a few minutes of inactivity. This now happens far less frequently, which can really be worth a lot for the user experience.

So you see: It's unfortunately not as black and white as we'd love it to be. We want to make our users happy while at the same time providing the security they expect from a modern software product. I believe that our current implementation fits that sweet-spot quite well.

**Comment by GiantCrocodile** [comment]
Thanks for your answer in detail @lukasbestle!
