### ISSUE TITLE
Try page: Offer Plaintkit side-by-side with Starterkit

### ISSUE THREAD

**Issue by distantnative** [getkirby/getkirby.com#760]
@bastianallgeier and I talked with some developers about how the starterkit isn't really anymore the one to pick when starting a new project as it features so much example code, documentation etc.

I think, we should emphasize the plaint more as the go-to download for new projects and clearly highlight the starterkit more as an entry point for new developers to learn about Kirby, play around, explore... but not for starting new projects necessarily.

**Comment by texnixe** [comment]
Do seasoned developers actually download the Kit from the homepage? I would have thought that people already familiar with Kirby either go the repo, install with Composer or Git?

The homepage download is a marketing tool. Someone new to Kirby who gets the Plainkit will probably be disappointed.

**Comment by distantnative** [comment]
At least the ones we talked to seemed to download it from the website.
Plus the issue that we don't highlight the plainkit that much at the moment. Some said it's quite some work to always clear the starterkit first (which of course they would not have to do with the plaint, but somehow they don't find it).

**Comment by distantnative** [comment]
I'm not arguing for just swapping them... 
But https://getkirby.com/try should probably feature both.

**Comment by texnixe** [comment]
> But https://getkirby.com/try should probably feature both.

Yes.

We already have both on the Getting started page, but the Try page should definitely have them both as well.

**Comment by texnixe** [comment]
We already have this issue here: https://github.com/getkirby/getkirby.com/issues/689

**Comment by lukasbestle** [comment]
I agree with @texnixe that we should keep the Starterkit as a marketing/demo site and should keep that one as the default. It's not the kit to "start" a new site, but a kit for Kirby "starters".

After all the "Try" page is for people who want to try Kirby for the first time before buying a license. It's not currently a general "Download" page where you can get everything we provide for download (which would e.g. include the Editor as well).

**Comment by distantnative** [comment]
@lukasbestle I’d argue that this might be how we like to perceive the try page, however that from anecdotes it is used as the fastest way to download Kirby for people who start new projects and are not as comfortable with composer or cloning git etc. (Which i think we have quite a good share in our community). So I’d strongly argue in favor of featuring plainkit and Starterkit on the Try page.

**Comment by lukasbestle** [comment]
That "because it's the fastest way to download Kirby" argument is a valid point. However I'm not sure if we should include all downloads directly on the Try page.

Idea: Add a link "Other downloads" below the big black "Download" button that leads to a page with all available downloads (Starterkit, Plainkit, Editor, link to the presskit...). The "Download" button could then be renamed to "Download Starterkit".

That way we can avoid blowing up the Try page with more and more buttons but still provide the downloads with a just few clicks from the homepage.

**Comment by distantnative** [comment]
I like that, I would still argue to include Plaint and Starterkit side by side. 
"because it's the fastest way to download Kirby" and that should apply to both options.

**Comment by texnixe** [comment]
Yes, even though semantically "try" sounds more like for people new to Kirby, that would also be my favorite, instead of having to go to yet another page.

**Comment by lukasbestle** [comment]
But what about the Editor or future products and other downloads then?

**Comment by texnixe** [comment]
We could still link to a downloads page...

**Comment by lukasbestle** [comment]
Right! Then I support this idea of having a Plainkit download link directly on the Try page. The only issue I see is that we either need to explain the difference directly on the page (which would duplicate the guide and also make the Try page a lot more verbose) or make the Plainkit less prominent (for example with a link instead of a button). Otherwise this will lead to confusion for new users.

**Comment by texnixe** [comment]
> The only issue I see is that we either need to explain the difference directly on the page 

We should nevertheless do that even if it means that we repeat ourselves. Just keep it as short as possible.

Starterkit: For newbies who want to learn.
Plainkit: For those who want to start from scratch.
