### ISSUE TITLE
Clarify behaviour of variables passed to render function

### ISSUE THREAD

**Issue by philipmarnef** [getkirby/getkirby.com#777]
I found the [entry in the docs](https://getkirby.com/docs/guide/templates/controllers#arguments-from-page-render-in-route) on passing variables from a route to a controller via the`$page->render()` method somewhat misleading. Any property in the array that's passed to the render method will be exposed in both the controller and the template as a global variable, regardless of your controller's arguments. 

The docs led me to believe you had to explicitly include these props as variables in the controller function and return them from there to expose them to the template.

**Comment by texnixe** [comment]
Hey @philipmarnef: I tested this again, and while it is true that the variables are passed through to the template, when using them in the controller you have to pass them as an argument, otherwise you get an undefined variable error.

If you think that works despite my little test, could you please provide a working example based on the Starterkit? Thank you.

Test setup:

Route in config:
```
    'routes' => [
        [
            'pattern' => 'notes/(:any)',
            'action'  => function ($uid) {
                $data = [
                    'test' => 'hello'
                ];
                if ($page = page('notes')->find($uid)) {
                    return $page->render($data);
                }
                return false;
            }
        ]
    ],
```

`note.php` controller that throws an error:

```
<?php

return function ($page) {

 
    return [
        'test' => $test
    ];
};
```

Working `note.php` controller:

```
<?php

return function ($page, $test) {

 
    return [
        'test' => $test
    ];
};
```

**Comment by philipmarnef** [comment]
@texnixe You are right. I can't remember what I was doing at the time of posting, but checked a recent project where I used `render()` in a route and if I don't pass the variable in the controller function it does indeed throw an error. I probably got that mixed up somehow.
