### ISSUE TITLE
Last time modified timestamp + download button for legal docs

### ISSUE THREAD

**Issue by GiantCrocodile** [getkirby/getkirby.com#782]
It would be nice if the official Kirby 3 site offers

- a download button for a PDF version of the legal texts (ToS, license stuff like https://getkirby.com/license, privacy policy, etc.)
- has a HTML5 metadata field about the last time modified timestamp of the page

This will make it easier to preserve the information long term and to understand when and if a modification did happen.

Thank you!

**Comment by lukasbestle** [comment]
> a download button for a PDF version of the legal texts (ToS, license stuff like https://getkirby.com/license, privacy policy, etc.)

The Kirby site has pretty solid print styles, so the best way would be to print the pages you want to preserve to PDF. A download button wouldn't do anything else either.

You can also follow the changes in this repo as all changes to the site are publicly documented here. This means that you can access any state of those pages even after the pages have been changed.

> has a HTML5 metadata field about the last time modified timestamp of the page

Do you mean `<meta http-equiv="Last-Modified" ...>`? That won't really be semantic though as the HTML may change independently from the content because of template changes etc.

Again: Best way to keep track of changes is the Git history of this repo. We also publish larger changes in the forum, like [in this case](https://forum.getkirby.com/t/update-to-the-kirby-end-user-license-agreement/12682).
