### ISSUE TITLE
Cookbook idea: make your IDEs intellisense work with Kirby

### ISSUE THREAD

**Issue by bnomei** [getkirby/getkirby.com#890]
if type of object is known autocompletion/intellisense works out of the box.

**controller**
```php
<?php
return function (Kirby\Cms\Site $site, Kirby\Cms\Page $page, Kirby\Cms\App $kirby) {
    // ...
}
```

**templates or snippets**
```php
<?php
/** @var Kirby\Cms\App $kirby */
/** @var Kirby\Cms\Site $site */
/** @var Kirby\Cms\Page $page */
$page->children(); // <-- works now
```

**Comment by medienbaecker** [comment]
Is it even possible to make it work in Kirby's current state? I started to look into this and wanted to document my journey for a cookbook recipe.
PHPDoc comments are relatively new to me, but it seems like there are quite a few functions with missing return types? For example this simple menu is probably something that everybody uses sooner or later:

```php

<?php
/**
 * @var \Kirby\Cms\Pages $pages
 * @var \Kirby\Cms\Page $page
 */
?>

<?php foreach($pages->listed() as $p): ?>
  <li>
    <a href="<?= $p->url() ?>">
      <?= $p->title() ?>
    </a>
  </li>
<?php endforeach ?>
```

The [listed()](https://github.com/getkirby/kirby/blob/main/src/Cms/Pages.php#L358-L364) function is missing a return type, so my IDE doesn't know that `$p` is a `Kirby\Cms\Page`.

If I add `@return \Kirby\Cms\Pages|\Kirby\Cms\Page[]` to the function it works. Is there something I'm missing? Do you add type hints for every variable you use? Does anybody even bother with this?

**Comment by texnixe** [comment]
> The [listed()](https://github.com/getkirby/kirby/blob/main/src/Cms/Pages.php#L358-L364) function is missing a return type

No?

```
	/**
	 * Returns all listed pages in the collection
	 */
	public function listed(): static
	{
		return $this->filter('isListed', '==', true);
	}

```

But yes, for variables that are not clear for some reason, you would have to add those comments. It can get quite cumbersome, though, if you have a lot of such variables.

**Comment by medienbaecker** [comment]
Sorry if I'm not using the right terminology. I meant this:

```diff
**
  * Returns all listed pages in the collection
+  * @return \Kirby\Cms\Pages|\Kirby\Cms\Page[]
  */
public function listed(): static
{
  return $this->filter('isListed', '==', true);
}

```

**Comment by texnixe** [comment]
Hm, why would you need the additional doc comment here when the method itself has a return type hint?

For me, this works fine without adding something in the PHPDoc comments:

<img width="569" alt="Bildschirmfoto 2024-04-10 um 19 27 51" src="https://github.com/getkirby/getkirby.com/assets/5312492/9cf225f5-4c32-40f4-884c-c602055f3537">

**Comment by medienbaecker** [comment]
Ah, interesting. Is that PHPStorm?

**Comment by texnixe** [comment]
> Ah, interesting. Is that PHPStorm?
Yes.

**Comment by medienbaecker** [comment]
Okay. So what you're saying is you get properly hinted `$p` variables? All the page methods are available? That means for some reason PHPStorm can find the `filter()` function inside of the `listed()` function and get the type from there. I guess I'll have to check out PHPStorm and continue my journey there.

**Comment by distantnative** [comment]
@medienbaecker I think we might have found a good way how to make IDEs understand the items of our collections (e.g. pages) inside loops: https://github.com/getkirby/kirby/pull/6391

Likely needs a plugin in your IDE to work, e.g. Intelephense, PHP Tools or similar.

**Comment by medienbaecker** [comment]
I tried PHPStorm and it doesn't know `$p` is a `\Kirby\Cms\Page`. If I understand it correctly there's only two ways to get true autocompletion in IDEs. I'll use the `children()` function as an example:

### 1. Adding explicit PHPDocs to the functions

Additionally to the already existing `Pages` type, we have to make clear that it returns a collection of `Page` objects by adding `Pages|Page[]` as a PHPDoc annotation:

```php
/**
 * Returns all published children
 * @return Pages|Page[]
 */
public function children(): Pages
{
  return $this->children ??= Pages::factory($this->inventory()['children'], $this);
}
```

### 2. Adding inline PHPDoc annotation for every variable

In order for the IDE to understand the variables inside of a collection without explicit PHPDocs in the functions, we have to ad inline PHPDoc annotations like this:

```php
<?php
  /** @var \Kirby\Cms\Page $p */
  foreach ($site->children() as $p) :
?>
<li>
  <a href="<?= $p->url() ?>">
    <?= $p->title() ?>
  </a>
</li>
<?php endforeach ?>
```

Because some methods are inherited by e.g. the general [Collection](https://github.com/getkirby/kirby/blob/main/src/Cms/Collection.php) class, it might be impossible to add the return types to every function.

**Comment by medienbaecker** [comment]
Hah, what a timing @distantnative. I'll have a look at that promising looking PR…

**Comment by distantnative** [comment]
Adding `Pages|Page[]` works for your case but as far as I see is a hack that we can't follow in the core as the method actually doesn't return an array of `Page` objects (what your return type tells the IDE). It helps the IDE to think inside a loop it will be a `Page`, but overall it's not quite correct. That's why we need to dig deeper and make the IDE actually understand what the underlying `ArrayIterator` of those collections returns https://github.com/getkirby/kirby/pull/6391/files#diff-added8fc2596bad641b0b11c5c38fffb1512a9be9279c7c09c86fec54618217dR42

**Comment by distantnative** [comment]
PR works at least for me in VSCode with Intelephense:

<img width="403" alt="Screenshot 2024-04-11 at 10 46 08" src="https://github.com/getkirby/getkirby.com/assets/3788865/6a287cd3-4cb1-4108-a86e-d94d573dad77">

**Comment by medienbaecker** [comment]
That's amazing, great work! I think this change makes a big difference ❤️ 

Works perfectly fine in PHPStorm, too:

![CleanShot 2024-04-11 at 10 53 09@2x](https://github.com/getkirby/getkirby.com/assets/7975568/7e9cbf4a-336d-4e40-9d7c-f76ebdea729b)
