### ISSUE TITLE
$file->size() not present in the docs

### ISSUE THREAD

**Issue by yandodov** [getkirby/getkirby.com#925]
I wanted to get the size of a `File` object and went to [the docs](https://getkirby.com/docs/reference/objects/file?advanced=yes) to look for a method that gives me that, but I couldn't find it, even in the Advanced section.

I decided to just try `$file->size()` and it worked. I think this should be mentioned in the docs.

**Comment by yandodov** [comment]
I just noticed that `$file->name()` is also missing.

**Comment by lukasbestle** [comment]
Good point!

I was confused as well when trying to find out why they specifically are not listed, but the reason is: The methods are defined in the `Kirby\Toolkit\File` class, which is extended by `Kirby\Image\Image`, an object of which is returned by `$file->asset()`, which gets called in `$file->__call()` when a method gets called that isn't defined in `Kirby\Cms\File` directly. So a lot of steps until the methods actually get called, which means that our reference can't automatically trace that back.

We can fix this by manually documenting the missing methods.

**Comment by distantnative** [comment]
Duplicate of https://github.com/getkirby/getkirby.com/issues/666
