### ISSUE TITLE
Error in next, prev, nextListed, prevListed docs

### ISSUE THREAD

**Issue by sylvainjule** [getkirby/getkirby.com#976]
The expected argument for those methods is a Collection, while the examples mention sort arguments: [/docs/reference/objects/page/next#example__using-sort-field](https://getkirby.com/docs/reference/objects/page/next#example__using-sort-field)

```php
// doesn't work
if($next = $page->next('date', 'desc')):

// works
if($next = $page->next($page->siblings()->sortBy('date', 'desc')):
```

**Comment by distantnative** [comment]
@lukasbestle @texnixe 
My gut feeling is that both ways should be working. @sylvainjule is right that only the latter is currently implemented. But should we implement the other way or change the documentation?

**Comment by texnixe** [comment]
The documented sort field parameter was never implemented, so I'd change the documentation. If we want to sort, we can pass a sorted collection.

**Comment by lukasbestle** [comment]
I agree with @texnixe.

Support for passing sort arguments would be a nice convenience feature, but it would increase the complexity (sort arguments can have an arbitrary argument count, but the `$collection` argument can't, so there would need to be a bit of code magic involved – not too much, but enough so that I think we should first verify that this feature is really needed).

To be honest I don't think the complexity is worth it for this feature. After all the feature would be useless for collections that are not the sibling collection. But custom collections are common (be it only a `listed` collection). So the use-case would be limited and for that limited use-case the feature is not really worth it.

So I agree that we should remove it from the docs.
